#!/usr/bin/env bash
# scripts/audit-self-test.sh · audit script coverage self-test
# Generated by PRD-11 maintenance · 2026-05-12 · M-3 机制化(/prd-retro §13 Diff-2)
#
# 防 audit script 列表跟 manual SQL / schema / migration 数据源漂移
# 类比 TD-039 (manual_admin_rls.sql DISABLE 26 表 · audit script 验 13 表)
# + TD-042 (US-007 改列表后漏验 8 admin model · psql 实测全 RLS DISABLED 但 audit 假绿灯)
#
# 用法:
#   bash scripts/audit-self-test.sh            # 跑全部 self-test
#   pnpm audit:self-test                       # CI 集成(package.json scripts)
#
# 退出码 · 0 全过 / 1 至少 1 fail(audit script coverage gap)

set -uo pipefail

PASS=0
FAIL=0
WARN=0

ok()      { echo "  ✅ $1"; PASS=$((PASS + 1)); }
fail()    { echo "  ❌ $1"; FAIL=$((FAIL + 1)); }
warn()    { echo "  ⚠️  $1"; WARN=$((WARN + 1)); }
section() { echo ""; echo "━━━ $1 ━━━"; }

cd "$(dirname "$0")/.."

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  QuanQn audit script coverage self-test"
echo "  时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# === Test 1: audit-admin-rls-tables.sh 列表 vs manual_admin_rls.sql DISABLE 列表 ===
section "Test 1: audit-admin-rls-tables.sh coverage vs manual_admin_rls.sql"

if [[ ! -f prisma/migrations/manual_admin_rls.sql ]]; then
  warn "manual_admin_rls.sql 不存在 · skip test 1"
elif [[ ! -f scripts/audit-admin-rls-tables.sh ]]; then
  warn "audit-admin-rls-tables.sh 不存在 · skip test 1"
else
  SQL_TABLES=$(grep -oE 'ALTER TABLE +[a-zA-Z_]+' prisma/migrations/manual_admin_rls.sql 2>/dev/null | awk '{print $3}' | sort -u)
  AUDIT_TABLES=$(grep -oE '"[a-z_]+"' scripts/audit-admin-rls-tables.sh 2>/dev/null | tr -d '"' | grep -E "^admin_|^approval_|^prompt_|^user_quota|^quota_|^trending_|^deep_learn|^kpi_|^ip_account_|^invite_|^auto_review|^user_violation|^evolution_|^feature_|^system_|^ab_" | sort -u)

  missing=$(comm -23 <(echo "$SQL_TABLES") <(echo "$AUDIT_TABLES") 2>/dev/null)
  if [[ -n "$missing" ]]; then
    fail "audit-admin-rls-tables.sh 未验以下 manual_admin_rls.sql DISABLE 的表(可能 RLS 漂移漏 catch):"
    echo "$missing" | sed 's/^/    - /'
  else
    sql_count=$(echo "$SQL_TABLES" | wc -l | tr -d ' ')
    audit_count=$(echo "$AUDIT_TABLES" | wc -l | tr -d ' ')
    ok "audit-admin-rls-tables.sh 列表 ($audit_count 表) 跟 manual_admin_rls.sql ($sql_count 表) 全对齐"
  fi
fi

# === Test 2: audit script 引用的代码路径真存在(防 monorepo 拆分后 src/ 路径失效) ===
section "Test 2: audit script 引用路径存在(防 grep 假绿灯)"

# 检查 audit-redlines-admin.sh 引用的 apps/* 路径
if [[ -f scripts/audit-redlines-admin.sh ]]; then
  PATHS=$(grep -oE 'apps/(admin|api|web)/[a-zA-Z_./-]*' scripts/audit-redlines-admin.sh 2>/dev/null | sort -u | grep -v '\\$' | grep -v '\*')
  bad_paths=()
  for p in $PATHS; do
    # 去除末尾 / · 检查 dir
    p_clean=${p%/}
    if [[ ! -d "$p_clean" && ! -f "$p_clean" ]]; then
      # path 可能含 glob · 取 base dir 检查
      base=$(echo "$p" | sed 's|/[^/]*\*.*||')
      if [[ -n "$base" && ! -d "$base" ]]; then
        bad_paths+=("$p")
      fi
    fi
  done
  if [[ ${#bad_paths[@]} -gt 0 ]]; then
    fail "audit-redlines-admin.sh 引用以下路径不存在(grep 假绿灯风险):"
    for p in "${bad_paths[@]}"; do echo "    - $p"; done
  else
    ok "audit-redlines-admin.sh 路径全存在 · grep 真扫"
  fi
fi

# === Test 3: audit-admin-rls.ts(AST)引用的 routers/admin/ 真存在 ===
section "Test 3: audit-admin-rls.ts AST 检测目标存在"

if [[ -f scripts/audit-admin-rls.ts ]]; then
  if [[ -d apps/api/src/trpc/routers/admin ]]; then
    ok "audit-admin-rls.ts AST 目标 apps/api/src/trpc/routers/admin/ 存在"
  else
    fail "audit-admin-rls.ts AST 目标 apps/api/src/trpc/routers/admin/ 不存在 · AST 无文件可扫"
  fi

  # 检查 EXCEPTION 列表里 procedure 数 vs 实际 publicAdminProcedure procedure 数
  if command -v npx >/dev/null 2>&1; then
    if npx tsx scripts/audit-admin-rls.ts > /tmp/audit-self-test-ast.out 2>&1; then
      checked=$(grep -oE "Checked [0-9]+ procedure" /tmp/audit-self-test-ast.out | head -1 | grep -oE "[0-9]+")
      if [[ -n "$checked" && "$checked" -gt 0 ]]; then
        ok "audit-admin-rls.ts 实跑成功 · 扫到 $checked procedure"
      else
        warn "audit-admin-rls.ts 实跑成功但 0 procedure · 检查 EXCEPTION 列表"
      fi
    else
      warn "audit-admin-rls.ts 实跑失败 · 查 /tmp/audit-self-test-ast.out"
    fi
  fi
fi

# === Test 4: verify-prd-N.sh 引用的 audit script 存在 ===
section "Test 4: verify-prd-N.sh 引用 audit script 链完整"

for verify in scripts/verify-prd-*.sh; do
  [[ -f "$verify" ]] || continue
  prd_n=$(echo "$verify" | grep -oE 'prd-[0-9]+')
  # grep 出 bash scripts/audit-*.sh 引用
  refs=$(grep -oE 'scripts/audit-[a-zA-Z_-]+\.(sh|ts)' "$verify" 2>/dev/null | sort -u)
  bad_refs=()
  for r in $refs; do
    [[ -f "$r" ]] || bad_refs+=("$r")
  done
  if [[ ${#bad_refs[@]} -gt 0 ]]; then
    fail "$verify 引用以下 audit script 不存在:"
    for r in "${bad_refs[@]}"; do echo "    - $r"; done
  else
    ref_count=$(echo "$refs" | grep -c . || echo 0)
    ok "$verify 引用 $ref_count audit script · 全存在"
  fi
done

# === Summary ===
section "Summary"
echo "  ✅ PASS: $PASS"
echo "  ⚠️  WARN: $WARN"
echo "  ❌ FAIL: $FAIL"
echo ""

if [[ $FAIL -eq 0 ]]; then
  echo "🎉 audit script coverage self-test 全过 · 无 audit drift 风险"
  exit 0
else
  echo "❌ audit script coverage 漂移 · $FAIL 项失败 · 必修(防 audit 假绿灯)"
  exit 1
fi
