/**
 * SCOPED 原型 · shadow router codegen(仅 App router 输出类型)
 *
 * 用 TS Compiler API 在 api 原生上下文(@/ 可解析)算出 inferRouterOutputs<AppRouter>,
 * 用【深度受限的递归打印器】把它打成自包含类型(@/ / import() 全消失,递归/JSON 类型超深 → 收敛成 unknown),
 * emit 到 packages/clients/src/router-types.generated.ts。
 * 目的:证明 "从真 router 生成扁平自包含 shadow" 的核心闭环可落地(generate → typecheck → 比对)。
 *
 * 运行:node scripts/codegen-shadow.cjs
 */
const ts = require('typescript');
const fs = require('fs');
const path = require('path');

const MAX_DEPTH = 8; // 超此深度的嵌套 → unknown(收敛递归/JSON 爆炸)
const MAX_PROPS = 80; // 单对象属性数超此 → unknown(防异常大类型)

const probePath = path.resolve('apps/api/src/__codegen_app_outputs.ts');
fs.writeFileSync(
  probePath,
  `import type { inferRouterOutputs } from '@trpc/server';\nimport type { AppRouter } from '@/trpc/routers/_app';\nexport type __AppOutputs = inferRouterOutputs<AppRouter>;\n`,
);

const cfgPath = path.resolve('apps/api/tsconfig.json');
const cfg = ts.readConfigFile(cfgPath, ts.sys.readFile);
const parsed = ts.parseJsonConfigFileContent(cfg.config, ts.sys, path.dirname(cfgPath));
const program = ts.createProgram([...parsed.fileNames, probePath], parsed.options);
const checker = program.getTypeChecker();
const sf = program.getSourceFile(probePath);
const alias = sf.statements.find((s) => ts.isTypeAliasDeclaration(s) && s.name.text === '__AppOutputs');
const rootType = checker.getDeclaredTypeOfSymbol(checker.getSymbolAtLocation(alias.name));

const PRIM =
  ts.TypeFlags.String |
  ts.TypeFlags.Number |
  ts.TypeFlags.Boolean |
  ts.TypeFlags.Null |
  ts.TypeFlags.Undefined |
  ts.TypeFlags.Void |
  ts.TypeFlags.StringLiteral |
  ts.TypeFlags.NumberLiteral |
  ts.TypeFlags.BooleanLiteral |
  ts.TypeFlags.Any |
  ts.TypeFlags.Unknown |
  ts.TypeFlags.Never |
  ts.TypeFlags.Enum |
  ts.TypeFlags.EnumLiteral;

let capped = 0;
let procCount = 0;

function printType(type, depth) {
  if (type.flags & PRIM) return checker.typeToString(type, undefined, ts.TypeFormatFlags.NoTruncation);
  if (depth >= MAX_DEPTH) {
    capped++;
    return 'unknown';
  }
  if (checker.isArrayType(type)) {
    const el = checker.getTypeArguments(type)[0];
    return `Array<${printType(el, depth + 1)}>`;
  }
  if (type.isUnion()) {
    return type.types.map((t) => printType(t, depth)).join(' | ');
  }
  if (checker.isTupleType(type)) {
    return `[${checker.getTypeArguments(type).map((t) => printType(t, depth + 1)).join(', ')}]`;
  }
  if (type.isIntersection()) {
    return type.types.map((t) => printType(t, depth)).join(' & ');
  }
  const strIndex = checker.getIndexTypeOfType(type, ts.IndexKind.String);
  // 只取合法标识符名的属性(跳过 symbol/computed/内部 key)
  const props = checker.getPropertiesOfType(type).filter((p) => /^[A-Za-z_$][\w$]*$/.test(p.name));
  if (props.length === 0) {
    if (strIndex) return `Record<string, ${printType(strIndex, depth + 1)}>`;
    // 复杂的 0-named-prop 类型(函数/symbol 等)→ 收敛 unknown,不调 typeToString(避免 ... 截断标记进生成物)
    capped++;
    return 'unknown';
  }
  if (props.length > MAX_PROPS) {
    capped++;
    return 'unknown';
  }
  const parts = props.map((p) => {
    const pt = checker.getTypeOfSymbolAtLocation(p, alias);
    const opt = p.flags & ts.SymbolFlags.Optional ? '?' : '';
    if (depth === 1) procCount++; // depth1 = 每个 router 下的 procedure
    return `  ${'  '.repeat(depth)}${p.name}${opt}: ${printType(pt, depth + 1)};`;
  });
  const idx = strIndex ? `\n  ${'  '.repeat(depth)}[key: string]: ${printType(strIndex, depth + 1)};` : '';
  return `{\n${parts.join('\n')}${idx}\n${'  '.repeat(depth)}}`;
}

const body = printType(rootType, 0);
const out = `// GENERATED by scripts/codegen-shadow.cjs — DO NOT EDIT BY HAND.
// 从真 AppRouter 自动派生的输出类型(自包含、深度受限)。原型阶段:仅 App router 输出。
export interface GeneratedAppOutputs ${body}
`;
fs.writeFileSync(path.resolve('packages/clients/src/router-types.generated.ts'), out);
fs.unlinkSync(probePath);

console.log(`✅ 生成完成 · procedure 数≈${procCount} · 深度/大小收敛成 unknown 的次数=${capped}`);
console.log(`   输出 → packages/clients/src/router-types.generated.ts (${out.length} 字符)`);
