#!/usr/bin/env bash
# scripts/verify-prd-10.sh — PRD-10 P9.0 admin foundation 可重复验收脚本
# Generated by /goal-verify · 2026-05-12 · 7/7 US PASSED
#
# 包装 audit-redlines-admin.sh + audit-admin-rls-tables.sh + audit-admin-rls.ts
# + 关键文件存在 + 16 placeholder + admin-integration + typecheck/lint
#
# 用法:
#   bash scripts/verify-prd-10.sh                    # 默认 · 静态 + 集成测试
#   SKIP_INTEGRATION=1 bash scripts/verify-prd-10.sh # 跳过 admin-integration(DB 不在线)
#   SKIP_TYPECHECK=1 bash scripts/verify-prd-10.sh   # 跳过 typecheck/lint(快速 check)
#
# 退出码 · 0 全过 / 1 至少 1 fail

set -uo pipefail  # 允许 fail() 后继续(不 -e)

PASS=0
FAIL=0
WARN=0
SKIPPED=0

ok()      { echo "  ✅ PASS: $1"; PASS=$((PASS + 1)); }
fail()    { echo "  ❌ FAIL: $1"; FAIL=$((FAIL + 1)); }
warn()    { echo "  ⚠️  WARN: $1"; WARN=$((WARN + 1)); }
skip()    { echo "  ⏭️  SKIP: $1"; SKIPPED=$((SKIPPED + 1)); }
section() { echo ""; echo "━━━ $1 ━━━"; }

# 切到项目根(脚本可从任意目录跑)
cd "$(dirname "$0")/.."

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  QuanAn PRD-10 P9.0 admin foundation · 可重复验收"
echo "  起点: $(pwd) · 时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# === §1 monorepo workspace 结构(US-001 · ARCHITECTURE §1.4b C)===
section "§1 monorepo workspace 结构(US-001)"

[[ -f pnpm-workspace.yaml ]] && ok "pnpm-workspace.yaml 存在" || fail "pnpm-workspace.yaml 缺失"

for sub in apps/admin apps/api apps/web packages/clients packages/schemas packages/ui; do
  if [[ -f "$sub/package.json" ]]; then
    name=$(grep -oE '"@quanan/[a-z]+"' "$sub/package.json" 2>/dev/null | head -1)
    if [[ -n "$name" ]]; then
      ok "$sub 子项目 $name"
    else
      warn "$sub 存在但无 @quanan/* name"
    fi
  else
    fail "$sub/package.json 缺失"
  fi
done

# === §2 RLS 双向验证(US-001 · D-067 + LD-A3)===
section "§2 RLS 双向验证(US-001 · D-067 + LD-A3)"

if bash scripts/audit-admin-rls-tables.sh > /tmp/verify-prd10-rls.out 2>&1; then
  if grep -q "PASS: all RLS states verified" /tmp/verify-prd10-rls.out; then
    admin_n=$(grep -oE "Admin tables verified.*[0-9]+/[0-9]+" /tmp/verify-prd10-rls.out | head -1)
    main_n=$(grep -oE "Main tables verified.*[0-9]+/[0-9]+" /tmp/verify-prd10-rls.out | head -1)
    ok "audit-admin-rls-tables · $admin_n + $main_n · 0 mismatches"
  else
    fail "audit-admin-rls-tables.sh 输出无 'PASS: all RLS states verified'"
  fi
else
  fail "audit-admin-rls-tables.sh exit ≠ 0 · 查 /tmp/verify-prd10-rls.out"
fi

# === §3 audit-redlines-admin.sh · 5 LD-A + 6 R-A(US-007 · AGENTS §10)===
section "§3 audit-redlines-admin.sh · 5 LD-A + 6 R-A(US-007 · AGENTS §10)"

if bash scripts/audit-redlines-admin.sh > /tmp/verify-prd10-redlines.out 2>&1; then
  if grep -q "ALL PASS · 5 LD-A + 6 R-A" /tmp/verify-prd10-redlines.out; then
    ok "audit-redlines-admin · ALL PASS · 5 LD-A + 6 R-A"
  else
    fail "audit-redlines-admin.sh 输出无 'ALL PASS · 5 LD-A + 6 R-A'"
  fi
else
  fail "audit-redlines-admin.sh exit ≠ 0 · 查 /tmp/verify-prd10-redlines.out"
fi

# === §4 adminProcedure AST 检测 6 闸(US-003 · LD-A3)===
section "§4 audit-admin-rls.ts (AST) · 6 闸链 0 violations(US-003 · LD-A3)"

if command -v npx >/dev/null 2>&1; then
  if npx tsx scripts/audit-admin-rls.ts > /tmp/verify-prd10-ast.out 2>&1; then
    if grep -q "0 violations" /tmp/verify-prd10-ast.out; then
      proc_n=$(grep -oE "Checked [0-9]+ procedure" /tmp/verify-prd10-ast.out | head -1)
      ok "audit-admin-rls.ts · $proc_n · 0 violations"
    else
      fail "audit-admin-rls.ts 输出无 '0 violations'"
    fi
  else
    fail "audit-admin-rls.ts exit ≠ 0 · 查 /tmp/verify-prd10-ast.out"
  fi
else
  skip "npx 未安装 · 跳过 AST 检测"
fi

# === §5 关键 admin 文件存在(US-001~005 实施核心)===
section "§5 关键 admin 文件存在(25 文件)"

REQUIRED_FILES=(
  # apps/admin SPA(US-001 + US-005)
  "apps/admin/vite.config.ts"
  "apps/admin/package.json"
  "apps/admin/src/layouts/AdminLayout.tsx"
  "apps/admin/src/components/admin/TopBar.tsx"
  "apps/admin/src/components/admin/Sidebar.tsx"
  "apps/admin/src/components/admin/AuditDrawer.tsx"
  "apps/admin/src/components/admin/StatusBar.tsx"
  "apps/admin/src/lib/admin-routes.ts"
  "apps/admin/src/pages/Login.tsx"
  "apps/admin/src/styles/admin.css"
  # apps/api admin 鉴权(US-002 + US-003)
  "apps/api/src/lib/auth/lucia-admin.ts"
  "apps/api/src/lib/auth/oauth-admin-factory.ts"
  "apps/api/src/lib/auth/oauth-admin-mock.ts"
  "apps/api/src/lib/auth/oauth-admin-google.ts"
  "apps/api/src/trpc/routers/admin/index.ts"
  "apps/api/src/trpc/routers/admin/auth.ts"
  # 6 闸 middleware + auditLog(US-001 stub + US-003 真接 + US-004)
  "apps/api/src/trpc/middleware/admin/adminAuth.ts"
  "apps/api/src/trpc/middleware/admin/roleCheck.ts"
  "apps/api/src/trpc/middleware/admin/ipWhitelist.ts"
  "apps/api/src/trpc/middleware/admin/mfaCheck.ts"
  "apps/api/src/trpc/middleware/admin/adminRLS.ts"
  "apps/api/src/trpc/middleware/admin/approvalGateCheck.ts"
  "apps/api/src/trpc/middleware/admin/auditLog.ts"
  "apps/api/src/trpc/procedures/admin.ts"
  "apps/api/src/services/admin/admin-audit-service.ts"
  "apps/api/src/lib/admin/audit-helpers.ts"
  # RLS migration(US-001 · D-067)
  "prisma/migrations/manual_admin_rls.sql"
)
MISSING=()
for f in "${REQUIRED_FILES[@]}"; do
  [[ -f "$f" ]] || MISSING+=("$f")
done
if [[ ${#MISSING[@]} -eq 0 ]]; then
  ok "${#REQUIRED_FILES[@]} 关键 admin 文件全部存在"
else
  fail "${#MISSING[@]} 文件缺失: ${MISSING[*]}"
fi

# === §6 16 sidebar 域 placeholder + admin-routes.ts metadata(US-005 · D-066)===
section "§6 16 sidebar 域 + admin-routes.ts metadata(US-005 · D-066)"

placeholder_count=$(ls apps/admin/src/pages/admin/placeholder/*.tsx 2>/dev/null | wc -l | tr -d ' ')
if [[ "$placeholder_count" == "16" ]]; then
  ok "16 placeholder 严格 16 个"
else
  fail "placeholder 数 $placeholder_count ≠ 16(PRD §1 US-005)"
fi

metadata_count=$(grep -cE "path: '/admin/" apps/admin/src/lib/admin-routes.ts 2>/dev/null || echo 0)
if [[ "$metadata_count" == "16" ]]; then
  ok "admin-routes.ts metadata 16 path 严格 16 个"
else
  fail "admin-routes.ts metadata $metadata_count ≠ 16"
fi

# === §7 关键反例 grep · multi-layer 防护(US-002 R3 · REJ-026 · LD-A1)===
section "§7 关键反例 grep · multi-layer 防护(US-002 R3 · REJ-026 · LD-A1)"

# REJ-026 · admin:session: namespace
if grep -q "admin:session:" apps/api/src/lib/auth/lucia-admin.ts 2>/dev/null; then
  ok "REJ-026 · lucia-admin 用 admin:session: namespace"
else
  fail "REJ-026 · lucia-admin 未含 'admin:session:' · LD-A1 违反"
fi

# R3 · prod startup gate
if grep -q "OAUTH_PROVIDER=mock not allowed in production" apps/api/src/lib/auth/oauth-admin-factory.ts 2>/dev/null; then
  ok "R3 Layer 1 · factory prod startup gate(防 mock 误进 prod)"
else
  fail "R3 Layer 1 · factory 缺 prod startup gate"
fi

# R3 · UI mock button DEV-only
if grep -q "import.meta.env.DEV" apps/admin/src/pages/Login.tsx 2>/dev/null; then
  ok "R3 Layer 2 · Login.tsx mock 按钮 import.meta.env.DEV 包"
else
  fail "R3 Layer 2 · Login.tsx mock 按钮缺 DEV guard"
fi

# LD-A3 · adminRLS set_config 真生效
if grep -q "set_config.*app.role.*admin" apps/api/src/trpc/middleware/admin/adminRLS.ts 2>/dev/null; then
  ok "LD-A3 · adminRLS.ts 含 set_config('app.role','admin') 真生效"
else
  fail "LD-A3 · adminRLS.ts 缺 set_config · 数据隔离漏"
fi

# R-A4 · admin_audit_log append-only
update_count=$(grep -rEn "prisma\.adminAuditLog\.(update|delete|upsert)" apps/api/src/ 2>/dev/null | wc -l | tr -d ' ')
if [[ "$update_count" == "0" ]]; then
  ok "R-A4 · admin_audit_log append-only · 0 UPDATE/DELETE/UPSERT 命中"
else
  fail "R-A4 · 发现 $update_count 处 adminAuditLog.update/delete/upsert · 违反 append-only"
fi

# === §8 admin 集成测试(US-002 + US-004 + US-006 · 10 case)===
section "§8 admin 集成测试(10 case · auth-flow + audit-log-write + rls-bypass)"

if [[ "${SKIP_INTEGRATION:-0}" == "1" ]]; then
  skip "SKIP_INTEGRATION=1 · 跳过(DB 不在线时使用)"
else
  if command -v pnpm >/dev/null 2>&1; then
    if pnpm test:admin-integration > /tmp/verify-prd10-integration.out 2>&1; then
      # vitest 输出格式 "Tests N passed"
      tests_line=$(grep -E "Tests +[0-9]+ passed" /tmp/verify-prd10-integration.out | tail -1)
      if [[ -n "$tests_line" ]]; then
        ok "admin-integration · $tests_line"
      else
        warn "admin-integration exit 0 但格式异常 · 查 /tmp/verify-prd10-integration.out"
      fi
    else
      fail "admin-integration 失败 · 查 /tmp/verify-prd10-integration.out"
    fi
  else
    skip "pnpm 未安装 · 跳过集成测试"
  fi
fi

# === §9 typecheck + lint 收官硬门禁(US-007)===
section "§9 typecheck + lint 收官硬门禁(US-007)"

if [[ "${SKIP_TYPECHECK:-0}" == "1" ]]; then
  skip "SKIP_TYPECHECK=1 · 跳过 typecheck + lint"
else
  if command -v pnpm >/dev/null 2>&1; then
    if pnpm typecheck > /tmp/verify-prd10-typecheck.out 2>&1; then
      ok "pnpm typecheck · 6 ws 0 errors"
    else
      fail "pnpm typecheck 失败 · 查 /tmp/verify-prd10-typecheck.out"
    fi

    if pnpm lint --max-warnings=0 > /tmp/verify-prd10-lint.out 2>&1; then
      ok "pnpm lint --max-warnings=0 · 0 warnings"
    else
      fail "pnpm lint 失败 · 查 /tmp/verify-prd10-lint.out"
    fi
  else
    skip "pnpm 未安装 · 跳过 typecheck + lint"
  fi
fi

# === Summary ===
section "Summary"
echo "  ✅ PASS: $PASS"
echo "  ⚠️  WARN: $WARN"
echo "  ❌ FAIL: $FAIL"
echo "  ⏭️  SKIP: $SKIPPED"
echo ""

if [[ $FAIL -eq 0 ]]; then
  echo "🎉 PRD-10 P9.0 admin foundation · 全部验收通过(零回归)"
  echo "   ADMIN §8.2 退出条件 + AGENTS §10 5 LD-A + 6 R-A + D-059~D-068 全 PASS"
  exit 0
else
  echo "❌ PRD-10 验收失败 · 详查 /tmp/verify-prd10-*.out"
  exit 1
fi
