#!/usr/bin/env bash
# scripts/verify-prd-12.sh — PRD-12 P9.2 content-review domains 可重复验收脚本
# Generated by US-013 · 2026-05-13 · 13/13 US PASSED
#
# 包装 audit-redlines-admin.sh + audit-admin-rls-tables.sh + audit-admin-rls.ts
# + PRD-12 文件存在 check + 2 placeholder 已删 + 2 路由 prd:12
# + ★ LD-A-5 grep multi-layer(workers 禁止直写 trendingItem/deepLearningArchive)
# + admin-integration + typecheck/lint
#
# 用法:
#   bash scripts/verify-prd-12.sh                    # 默认 · 静态 + 集成测试
#   SKIP_INTEGRATION=1 bash scripts/verify-prd-12.sh # 跳过 admin-integration(DB 不在线)
#   SKIP_TYPECHECK=1 bash scripts/verify-prd-12.sh   # 跳过 typecheck/lint(快速 check)
#
# fast mode = SKIP_INTEGRATION=1(仅 skip §8 + 浏览器 · keep 静态 audit §1-7 + §9)
# 退出码 · 0 全过 / 1 至少 1 fail

set -uo pipefail  # 允许 fail() 后继续(不 -e)

PASS=0
FAIL=0
WARN=0
SKIPPED=0

ok()      { echo "  ✅ PASS: $1"; PASS=$((PASS + 1)); }
fail()    { echo "  ❌ FAIL: $1"; FAIL=$((FAIL + 1)); }
warn()    { echo "  ⚠️  WARN: $1"; WARN=$((WARN + 1)); }
skip()    { echo "  ⏭️  SKIP: $1"; SKIPPED=$((SKIPPED + 1)); }
section() { echo ""; echo "━━━ $1 ━━━"; }

# 切到项目根(脚本可从任意目录跑)
cd "$(dirname "$0")/.."

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  QuanAn PRD-12 P9.2 content-review domains · 可重复验收"
echo "  起点: $(pwd) · 时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# === §1 monorepo workspace 结构 ===
section "§1 monorepo workspace 结构"

[[ -f pnpm-workspace.yaml ]] && ok "pnpm-workspace.yaml 存在" || fail "pnpm-workspace.yaml 缺失"

for sub in apps/admin apps/api apps/web packages/clients packages/schemas packages/ui; do
  if [[ -f "$sub/package.json" ]]; then
    name=$(grep -oE '"@quanan/[a-z]+"' "$sub/package.json" 2>/dev/null | head -1)
    if [[ -n "$name" ]]; then
      ok "$sub 子项目 $name"
    else
      warn "$sub 存在但无 @quanan/* name"
    fi
  else
    fail "$sub/package.json 缺失"
  fi
done

# === §2 RLS 双向验证(18 admin RLS=false + 15 main RLS=true · D-067 + LD-A3)===
section "§2 RLS 双向验证(D-067 + LD-A3)"

if bash scripts/audit-admin-rls-tables.sh > /tmp/verify-prd12-rls.out 2>&1; then
  if grep -q "PASS: all RLS states verified" /tmp/verify-prd12-rls.out; then
    admin_n=$(grep -oE "Admin tables verified.*[0-9]+/[0-9]+" /tmp/verify-prd12-rls.out | head -1)
    main_n=$(grep -oE "Main tables verified.*[0-9]+/[0-9]+" /tmp/verify-prd12-rls.out | head -1)
    ok "audit-admin-rls-tables · $admin_n + $main_n · 0 mismatches"
  else
    fail "audit-admin-rls-tables.sh 输出无 'PASS: all RLS states verified'"
  fi
else
  fail "audit-admin-rls-tables.sh exit ≠ 0 · 查 /tmp/verify-prd12-rls.out"
fi

# === §3 audit-redlines-admin.sh · 5 LD-A + 6 R-A(AGENTS §10)===
section "§3 audit-redlines-admin.sh · 5 LD-A + 6 R-A(AGENTS §10)"

if bash scripts/audit-redlines-admin.sh > /tmp/verify-prd12-redlines.out 2>&1; then
  if grep -q "ALL PASS · 5 LD-A + 6 R-A" /tmp/verify-prd12-redlines.out; then
    ok "audit-redlines-admin · ALL PASS · 5 LD-A + 6 R-A"
  else
    fail "audit-redlines-admin.sh 输出无 'ALL PASS · 5 LD-A + 6 R-A'"
  fi
else
  fail "audit-redlines-admin.sh exit ≠ 0 · 查 /tmp/verify-prd12-redlines.out"
fi

# === §4 adminProcedure AST 检测 6 闸(LD-A3)· ≥50 procedure 0 violations ===
section "§4 audit-admin-rls.ts (AST) · 6 闸链 ≥50 procedure 0 violations(LD-A3)"

if command -v npx >/dev/null 2>&1; then
  if npx tsx scripts/audit-admin-rls.ts > /tmp/verify-prd12-ast.out 2>&1; then
    if grep -q "0 violations" /tmp/verify-prd12-ast.out; then
      proc_n=$(grep -oE "Checked [0-9]+ procedure" /tmp/verify-prd12-ast.out | head -1)
      proc_count=$(echo "$proc_n" | grep -oE "[0-9]+" | head -1)
      if [[ -n "$proc_count" ]] && [[ "$proc_count" -ge 50 ]]; then
        ok "audit-admin-rls.ts · $proc_n · 0 violations(≥50 ✓)"
      elif [[ -n "$proc_count" ]]; then
        warn "audit-admin-rls.ts · $proc_n · 0 violations(但 <50 procedures · AC-4)"
      else
        ok "audit-admin-rls.ts · 0 violations"
      fi
    else
      fail "audit-admin-rls.ts 输出无 '0 violations'"
    fi
  else
    fail "audit-admin-rls.ts exit ≠ 0 · 查 /tmp/verify-prd12-ast.out"
  fi
else
  skip "npx 未安装 · 跳过 AST 检测"
fi

# === §5 PRD-12 关键文件存在(13 US 实施核心)===
section "§5 PRD-12 关键文件存在(US-001~013)"

PRD12_FILES=(
  # API routers (US-004 reviewTrending · US-009 reviewDeepLearn)
  "apps/api/src/trpc/routers/admin/review-trending.ts"
  "apps/api/src/trpc/routers/admin/review-deep-learn.ts"
  # Services (US-001~003 · US-007~008)
  "apps/api/src/services/admin/content-review/trending-auto-verdict.service.ts"
  "apps/api/src/services/admin/content-review/deep-learn-auto-verdict.service.ts"
  "apps/api/src/services/admin/content-review/pii-detection.service.ts"
  "apps/api/src/services/admin/content-review/banned-word.service.ts"
  "apps/api/src/services/admin/content-review/violation-detection.service.ts"
  # Jobs (US-012)
  "apps/api/src/jobs/admin/violation-detection.job.ts"
  # Workers (US-002 · US-003)
  "apps/api/src/workers/trending-scraper/worker.ts"
  "apps/api/src/workers/trending-scraper/queue.ts"
  "apps/api/src/workers/file-parser/worker.ts"
  "apps/api/src/workers/file-parser/queue.ts"
  # Admin UI — reviewTrending (US-005/006)
  "apps/admin/src/pages/reviewTrending/index.tsx"
  "apps/admin/src/pages/reviewTrending/TrendingReviewDrawer.tsx"
  "apps/admin/src/pages/reviewTrending/BatchActionBar.tsx"
  "apps/admin/src/pages/reviewTrending/AutoRuleConfigPanel.tsx"
  # Admin UI — reviewDeepLearn (US-010/011)
  "apps/admin/src/pages/reviewDeepLearn/index.tsx"
  "apps/admin/src/pages/reviewDeepLearn/DeepLearnReviewDrawer.tsx"
  "apps/admin/src/pages/reviewDeepLearn/UserViolationsTab.tsx"
  "apps/admin/src/pages/reviewDeepLearn/FilePreviewPanel.tsx"
)
MISSING_FILES=()
for f in "${PRD12_FILES[@]}"; do
  [[ -f "$f" ]] || MISSING_FILES+=("$f")
done
if [[ ${#MISSING_FILES[@]} -eq 0 ]]; then
  ok "${#PRD12_FILES[@]} PRD-12 关键文件全存在"
else
  fail "${#MISSING_FILES[@]} 文件缺失: ${MISSING_FILES[*]}"
fi

# adminRouter index.ts 同时挂 reviewTrending + reviewDeepLearn(AC-1)
if grep -q "reviewTrending: reviewTrendingRouter" apps/api/src/trpc/routers/admin/index.ts 2>/dev/null \
  && grep -q "reviewDeepLearn: reviewDeepLearnRouter" apps/api/src/trpc/routers/admin/index.ts 2>/dev/null; then
  ok "adminRouter index.ts 同时挂 reviewTrendingRouter + reviewDeepLearnRouter(AC-1)"
else
  fail "adminRouter index.ts 未正确挂 reviewTrending/reviewDeepLearn · AC-1 未满足"
fi

# 语义校验 1: review-trending.ts 导出 reviewTrendingRouter
if grep -q "export.*reviewTrendingRouter" apps/api/src/trpc/routers/admin/review-trending.ts 2>/dev/null; then
  ok "review-trending.ts 导出 reviewTrendingRouter(语义 ✓)"
else
  fail "review-trending.ts 未找到 reviewTrendingRouter export"
fi

# 语义校验 2: review-deep-learn.ts 导出 reviewDeepLearnRouter
if grep -q "export.*reviewDeepLearnRouter" apps/api/src/trpc/routers/admin/review-deep-learn.ts 2>/dev/null; then
  ok "review-deep-learn.ts 导出 reviewDeepLearnRouter(语义 ✓)"
else
  fail "review-deep-learn.ts 未找到 reviewDeepLearnRouter export"
fi

# 语义校验 3: violation-detection.service.ts 导出 detectViolationThresholds
if grep -q "detectViolationThresholds" apps/api/src/services/admin/content-review/violation-detection.service.ts 2>/dev/null; then
  ok "violation-detection.service.ts 含 detectViolationThresholds(US-012 AC-1)"
else
  fail "violation-detection.service.ts 缺 detectViolationThresholds"
fi

# 语义校验 4: violation-detection.job.ts 含 cron '0 4 * * *'(US-012 AC-1 错峰)
if grep -q "0 4 \* \* \*" apps/api/src/jobs/admin/violation-detection.job.ts 2>/dev/null; then
  ok "violation-detection.job.ts 含 cron '0 4 * * *' 错峰(US-012 AC-1)"
else
  fail "violation-detection.job.ts 缺 cron '0 4 * * *' · US-012 AC-1 未满足"
fi

# 语义校验 5: trending-auto-verdict.service.ts 含 runAutoVerdictForContent
if grep -q "runAutoVerdictForContent" apps/api/src/services/admin/content-review/trending-auto-verdict.service.ts 2>/dev/null; then
  ok "trending-auto-verdict.service.ts 含 runAutoVerdictForContent(US-001)"
else
  fail "trending-auto-verdict.service.ts 缺 runAutoVerdictForContent"
fi

# 语义校验 6: pii-detection.service.ts 含 PIIDetectionService
if grep -q "PIIDetectionService" apps/api/src/services/admin/content-review/pii-detection.service.ts 2>/dev/null; then
  ok "pii-detection.service.ts 含 PIIDetectionService class(US-007)"
else
  fail "pii-detection.service.ts 缺 PIIDetectionService"
fi

# === §6 2 placeholder 已删 + 2 路由 prd:12(AC-2/3)===
section "§6 placeholder 状态(2 PRD-12 已替换 / 8 PRD-13~14 保留)"

# reviewTrending placeholder 已删
if [[ -f "apps/admin/src/pages/admin/placeholder/reviewTrending.tsx" ]]; then
  fail "reviewTrending.tsx placeholder 仍存在 · AC-3 未满足"
else
  ok "reviewTrending placeholder 已删(或从未存在 · AC-3 满足)"
fi

# reviewDeepLearn placeholder 已删
if [[ -f "apps/admin/src/pages/admin/placeholder/reviewDeepLearn.tsx" ]]; then
  fail "reviewDeepLearn.tsx placeholder 仍存在 · AC-3 未满足"
else
  ok "reviewDeepLearn placeholder 已删(或从未存在 · AC-3 满足)"
fi

# 剩余 placeholder 严格 8 个(PRD-13~14 保留)
placeholder_count=$(ls apps/admin/src/pages/admin/placeholder/*.tsx 2>/dev/null | wc -l | tr -d ' ')
if [[ "$placeholder_count" == "8" ]]; then
  ok "残留 placeholder 严格 8 个(PRD-13~14 · 正确)"
else
  warn "残留 placeholder $placeholder_count ≠ 8 · 期望 PRD-13~14 的 8 个"
fi

# admin-routes.ts 2 路由 prd:12(AC-2)
prd12_route_count=$(grep -c "prd: 12" apps/admin/src/lib/admin-routes.ts 2>/dev/null || echo 0)
if [[ "$prd12_route_count" == "2" ]]; then
  ok "admin-routes.ts 严格 2 路由 prd: 12(/admin/reviewTrending + /admin/reviewDeepLearn · AC-2)"
else
  fail "admin-routes.ts prd: 12 路由 $prd12_route_count ≠ 2 · AC-2 未满足"
fi

# === §7 ★ LD-A-5 grep multi-layer 防护 ===
section "§7 ★ LD-A-5 grep multi-layer(workers 禁止直写 · approve 是唯一写入点)"

# trending-scraper/worker.ts: 0 命中 .trendingItem.create(LD-A-5 · US-002)
# 注: workers 用 trendingReviewQueue.create · 不应有 trendingItem.create(无论 prisma. 还是 tx.)
ts_create_count=$(grep "\.trendingItem\.create" apps/api/src/workers/trending-scraper/worker.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$ts_create_count" == "0" ]]; then
  ok "LD-A-5 · trending-scraper/worker.ts 0 命中 .trendingItem.create(LD-A-5 满足)"
else
  fail "LD-A-5 · trending-scraper/worker.ts $ts_create_count 命中 .trendingItem.create · 违反 LD-A-5"
fi

# file-parser/worker.ts: 0 命中 .deepLearningArchive.create(LD-A-5 · US-003)
# 注: workers 用 deepLearnReviewQueue.create · 不应有 deepLearningArchive.create
fp_create_count=$(grep "\.deepLearningArchive\.create" apps/api/src/workers/file-parser/worker.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$fp_create_count" == "0" ]]; then
  ok "LD-A-5 · file-parser/worker.ts 0 命中 .deepLearningArchive.create(LD-A-5 满足)"
else
  fail "LD-A-5 · file-parser/worker.ts $fp_create_count 命中 .deepLearningArchive.create · 违反 LD-A-5"
fi

# review-trending.ts: ≥1 命中 .trendingItem.create(approve 内 tx.trendingItem.create · 唯一写入点)
rt_create_count=$(grep "\.trendingItem\.create" apps/api/src/trpc/routers/admin/review-trending.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$rt_create_count" -ge 1 ]]; then
  ok "LD-A-5 · review-trending.ts $rt_create_count 命中 .trendingItem.create(approve 唯一写入点 ✓)"
else
  fail "LD-A-5 · review-trending.ts 0 命中 .trendingItem.create · approve 写入点缺失"
fi

# review-deep-learn.ts: ≥1 命中 .deepLearningArchive.create(approve 内 tx.deepLearningArchive.create · 唯一写入点)
rdl_create_count=$(grep "\.deepLearningArchive\.create" apps/api/src/trpc/routers/admin/review-deep-learn.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$rdl_create_count" -ge 1 ]]; then
  ok "LD-A-5 · review-deep-learn.ts $rdl_create_count 命中 .deepLearningArchive.create(approve 唯一写入点 ✓)"
else
  fail "LD-A-5 · review-deep-learn.ts 0 命中 .deepLearningArchive.create · approve 写入点缺失"
fi

# LD-A-5 扩展: violation-detection.service.ts 也不应直接 create trendingItem/deepLearningArchive
vd_ti=$(grep "\.trendingItem\.create\|\.deepLearningArchive\.create" apps/api/src/services/admin/content-review/violation-detection.service.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$vd_ti" == "0" ]]; then
  ok "LD-A-5 扩展 · violation-detection.service.ts 0 命中 trendingItem/deepLearningArchive.create"
else
  fail "LD-A-5 扩展 · violation-detection.service.ts $vd_ti 命中 · 违反 LD-A-5"
fi

# LD-A-5 扩展: trending-scraper 正确用 trendingReviewQueue.create(not trendingItem.create)
ts_queue=$(grep "\.trendingReviewQueue\.create" apps/api/src/workers/trending-scraper/worker.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$ts_queue" -ge 1 ]]; then
  ok "LD-A-5 扩展 · trending-scraper/worker.ts $ts_queue 命中 trendingReviewQueue.create(正确 review queue ✓)"
else
  fail "LD-A-5 扩展 · trending-scraper/worker.ts 未找到 trendingReviewQueue.create · 队列写入缺失"
fi

# LD-A-5 扩展: file-parser 正确用 deepLearnReviewQueue.create(not deepLearningArchive.create)
fp_queue=$(grep "\.deepLearnReviewQueue\.create" apps/api/src/workers/file-parser/worker.ts 2>/dev/null | wc -l | tr -d ' ')
if [[ "$fp_queue" -ge 1 ]]; then
  ok "LD-A-5 扩展 · file-parser/worker.ts $fp_queue 命中 deepLearnReviewQueue.create(正确 review queue ✓)"
else
  fail "LD-A-5 扩展 · file-parser/worker.ts 未找到 deepLearnReviewQueue.create · 队列写入缺失"
fi

# === §8 admin-integration(2 URL 200 · /admin/reviewTrending + /admin/reviewDeepLearn)===
section "§8 admin-integration(backend health · PRD-12 routes wired)"

if [[ "${SKIP_INTEGRATION:-0}" == "1" ]]; then
  skip "SKIP_INTEGRATION=1 · 跳过(fast mode · DB/服务不在线时使用)"
else
  if command -v pnpm >/dev/null 2>&1; then
    if pnpm test:admin-integration > /tmp/verify-prd12-integration.out 2>&1; then
      tests_line=$(grep -E "Tests +[0-9]+ passed" /tmp/verify-prd12-integration.out | tail -1)
      if [[ -n "$tests_line" ]]; then
        ok "admin-integration · $tests_line"
      else
        warn "admin-integration exit 0 但格式异常 · 查 /tmp/verify-prd12-integration.out"
      fi
    else
      fail "admin-integration 失败 · 查 /tmp/verify-prd12-integration.out"
    fi
  else
    skip "pnpm 未安装 · 跳过集成测试"
  fi
fi

# === §9 typecheck + lint 收官硬门禁(AC-9)===
section "§9 typecheck + lint 收官硬门禁(AC-9)"

if [[ "${SKIP_TYPECHECK:-0}" == "1" ]]; then
  skip "SKIP_TYPECHECK=1 · 跳过 typecheck + lint"
else
  if command -v pnpm >/dev/null 2>&1; then
    if pnpm typecheck > /tmp/verify-prd12-typecheck.out 2>&1; then
      ok "pnpm typecheck · 全 workspace 0 errors"
    else
      fail "pnpm typecheck 失败 · 查 /tmp/verify-prd12-typecheck.out"
    fi

    if pnpm lint --max-warnings=0 > /tmp/verify-prd12-lint.out 2>&1; then
      ok "pnpm lint --max-warnings=0 · 0 warnings"
    else
      warn "pnpm lint 有 warnings · 查 /tmp/verify-prd12-lint.out"
    fi

    # audit-self-test.sh 引用 4 audit 全存在
    if bash scripts/audit-self-test.sh > /tmp/verify-prd12-selftest.out 2>&1; then
      ok "audit-self-test.sh 全过 · 4 audit script 全存在"
    else
      fail "audit-self-test.sh 失败 · 查 /tmp/verify-prd12-selftest.out"
    fi
  else
    skip "pnpm 未安装 · 跳过 typecheck + lint"
  fi
fi

# === Summary ===
section "Summary"
echo "  ✅ PASS:    $PASS"
echo "  ⚠️  WARN:   $WARN"
echo "  ❌ FAIL:    $FAIL"
echo "  ⏭️  SKIP:   $SKIPPED"
echo ""

if [[ $FAIL -eq 0 ]]; then
  echo "🎉 PRD-12 P9.2 content-review domains · 全部验收通过(零回归)"
  echo "   ReviewTrending+ReviewDeepLearn · LD-A-5 多层防护 · 13 US PASSED"
  exit 0
else
  echo "❌ PRD-12 验收失败 · 详查 /tmp/verify-prd12-*.out"
  exit 1
fi
