/* eslint-disable */
// GENERATED by scripts/codegen-shadow.cjs — DO NOT EDIT BY HAND. Run `pnpm codegen:shadow`.
// 从真 AppRouter 自动生成的扁平自包含 shadow(取代手写镜像)。永远与后端同步、零漂移。
import { initTRPC } from '@trpc/server';
const _t = initTRPC.create();
declare const __stub: never;
type JsonValue = string | number | boolean | { [k: string]: JsonValue } | JsonValue[] | null;

const _gen = _t.router({
  auth: _t.router({
  me: _t.procedure.query((): { ok: false; error: "unauthenticated"; user?: undefined } | { ok: true; user: { id: number; email: string; name: string }; error?: undefined } => __stub),
  }),
  acquisitionVideo: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { sourceCopy: string; conversionGoal: string; platform?: undefined | string; duration?: undefined | "15s" | "30s" | "60s" | "180s" }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  aiVideo: _t.router({
  generateStoryboard: _t.procedure.input((x: unknown) => x as { sourceCopy: string; scenesCount: 6 | 5 | 8 | 7; imageStyle?: undefined | "vivid" | "natural" }).mutation((): { historyId: number; jobIds: Array<string>; scenesPlaceholder: Array<{ index: number; description: string; imagePromptEn: string; sceneImageUrl: null; status: "pending" }> } => __stub),
  dailyUsage: _t.procedure.query((): { count: number; limit: number } => __stub),
  jobStatus: _t.procedure.input((x: unknown) => x as { historyId: number }).query((): { total: number; completed: number; pending: number; failed: number; scenes: Array<{ error?: undefined | string; sceneImageUrl?: undefined | string; index: number; status: "pending" | "completed" | "failed" }> } => __stub),
  }),
  dailyTasks: _t.router({
  getToday: _t.procedure.query((): null | { id: number; accountId: number; agentId: string; modelUsed: null | string; isFallback: boolean; createdAt: Date; updatedAt: Date; taskDate: Date; tasks: JsonValue; completedCount: number; totalCount: number } => __stub),
  getHistory: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number }).query((): Array<{ id: number; accountId: number; agentId: string; modelUsed: null | string; isFallback: boolean; createdAt: Date; updatedAt: Date; taskDate: Date; tasks: JsonValue; completedCount: number; totalCount: number }> => __stub),
  regenerateToday: _t.procedure.mutation((): { ok: boolean; scheduledDate: string; jobId: string } => __stub),
  markCompleted: _t.procedure.input((x: unknown) => x as { dailyTaskId: number; taskId: string }).mutation((): { ok: boolean; completedCount: number; totalCount: number } => __stub),
  debugSeedTasks: _t.procedure.input((x: unknown) => x as { accountId: number; count: number }).mutation((): { ok: boolean; id: number; totalCount: number } => __stub),
  debugQueueStatus: _t.procedure.query((): { waiting: number; active: number; completed: number; failed: number } => __stub),
  }),
  evolution: _t.router({
  getProfile: _t.procedure.query((): null | { id: number; updatedAt: Date; autoEvolutionEnabled: boolean; currentDirection: string; level: string; feedbackCountGood: number; feedbackCountBad: number; feedbackCountTotal: number; satisfactionRate: null | number; latestInsight: JsonValue; deepLearningCount: number; lastEvolvedAt: null | Date; lastUpgradedAt: null | Date } => __stub),
  evolve: _t.procedure.input((x: unknown) => x as { agentId: string; rating: "good" | "bad"; rateableId: number; historyId?: undefined | number; rateableType?: undefined | string; comment?: undefined | string }).mutation((): { ok: boolean; feedbackId: number } => __stub),
  getConfig: _t.procedure.query((): { autoEvolutionEnabled: boolean; currentDirection: string; level: string } => __stub),
  updateConfig: _t.procedure.input((x: unknown) => x as { autoEvolutionEnabled?: undefined | false | true; currentDirection?: undefined | string }).mutation((): { ok: boolean; config: { autoEvolutionEnabled: boolean; currentDirection: string; level: string } } => __stub),
  history: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number }).query((): Array<{ id: number; content: JsonValue; createdAt: Date; triggerType: string; direction: string; levelBefore: null | string; levelAfter: null | string }> => __stub),
  recentFeedback: _t.procedure.input((x: unknown) => x as { agentId?: undefined | string; limit?: undefined | number }).query((): Array<{ rating: "good" | "bad"; traceId: null | string; id: number; agentId: string; createdAt: Date; comment: null | string }> => __stub),
  feedbackTrend: _t.procedure.input((x: unknown) => x as { days?: undefined | number }).query((): { data: Array<{ date: string; good: number; bad: number }>; days: number } => __stub),
  moduleRanking: _t.procedure.input((x: unknown) => x as { limit?: undefined | number }).query((): { ranking: Array<{ agentId: string; goodCount: number; badCount: number; satisfactionRate: number }> } => __stub),
  getInsightHistory: _t.procedure.query((): Array<{ id: number; content: JsonValue; createdAt: Date; triggerType: string; direction: string; levelBefore: null | string; levelAfter: null | string }> => __stub),
  getFeedbackTrend: _t.procedure.input((x: unknown) => x as { days?: undefined | number }).query((): Array<{ date: string; total: number; good: number; satisfactionRate: number }> => __stub),
  getModuleRanking: _t.procedure.input((x: unknown) => x as { limit?: undefined | number }).query((): { ranking: Array<{ agentId: string; goodCount: number; badCount: number; totalCalls: number; satisfactionRate: number }> } => __stub),
  debugQueueCount: _t.procedure.query((): { waiting: number } => __stub),
  debugSeedInsight: _t.procedure.mutation((): { ok: boolean; levelAfter: "L1" | "L2" | "L3" | "L4" | "L5" } => __stub),
  debugAssembleSystemPrompt: _t.procedure.query((): { systemPrompt: string } => __stub),
  }),
  ipAccounts: _t.router({
  list: _t.procedure.query((): Array<{ name: string; industry: string; platform: string; id: number; stage: string; personalInfo: null | string; followersRange: string; ipPositioning: null | string; isActive: boolean }> => __stub),
  active: _t.procedure.query((): null | { name: string; industry: string; platform: string; id: number; stage: string; personalInfo: null | string; followersRange: string; ipPositioning: null | string; isActive: boolean } => __stub),
  create: _t.procedure.input((x: unknown) => x as { name: string; industry: string; platform: string; stage?: undefined | string; personalInfo?: undefined | string; followersRange?: undefined | string; ipPositioning?: undefined | string }).mutation((): { name: string; industry: string; platform: string; id: number; stage: string; personalInfo: null | string; followersRange: string; ipPositioning: null | string; isActive: boolean } => __stub),
  update: _t.procedure.input((x: unknown) => x as { name?: undefined | string; industry?: undefined | string; platform?: undefined | string; accountId?: undefined | number; stage?: undefined | string; personalInfo?: undefined | string; followersRange?: undefined | string; ipPositioning?: undefined | string }).mutation((): null | { name: string; industry: string; platform: string; id: number; stage: string; personalInfo: null | string; followersRange: string; ipPositioning: null | string; isActive: boolean } => __stub),
  delete: _t.procedure.input((x: unknown) => x as { accountId: number }).mutation((): { ok: boolean } => __stub),
  switchActive: _t.procedure.input((x: unknown) => x as { accountId: number }).mutation((): { ok: boolean; activeAccountId: number } => __stub),
  smartRecommend: _t.procedure.input((x: unknown) => x as { industry: string }).mutation((): { platform: string; followersRange: string; ipPositioning: string; rationale: string; isFallback: boolean } => __stub),
  }),
  step3: _t.router({
  generatePackage: _t.procedure.input((x: unknown) => x as { platform: string; personalInfo: string; audience?: undefined | string; accountStatus?: undefined | string; force?: undefined | false | true }).mutation((): { ok: boolean; data: { result: JsonValue; isFallback: boolean; updatedAt: Date; stepKey: string; inputs: JsonValue; version: number } } => __stub),
  optimizeSection: _t.procedure.input((x: unknown) => x as { currentResult: Record<string, unknown> }).mutation((): { ok: boolean; data: { result: JsonValue; isFallback: boolean; updatedAt: Date; stepKey: string; inputs: JsonValue; version: number }; isFallback: boolean } => __stub),
  }),
  stepData: _t.router({
  get: _t.procedure.input((x: unknown) => x as { stepKey: string }).query((): null | { result: JsonValue; isFallback: boolean; updatedAt: Date; stepKey: string; inputs: JsonValue; version: number } => __stub),
  getAll: _t.procedure.query((): Array<{ result: JsonValue; isFallback: boolean; updatedAt: Date; stepKey: string; inputs: JsonValue; version: number }> => __stub),
  save: _t.procedure.input((x: unknown) => x as { stepKey: string; inputs: Record<string, unknown> }).mutation((): { ok: boolean; data: { result: JsonValue; isFallback: boolean; updatedAt: Date; stepKey: string; inputs: JsonValue; version: number } } => __stub),
  saveStream: _t.procedure.input((x: unknown) => x as { stepKey: "step5"; inputs: Record<string, unknown>; category: "traffic" | "monetize" | "persona" | "cognition" | "case" } | { stepKey: "step7"; inputs: Record<string, unknown> }).subscription((): AsyncGenerator<unknown> => __stub),
  progress: _t.procedure.query((): { completed: number; total: 9; completedSteps: Array<"step3" | "step5" | "step7" | "step1" | "step3b" | "step4" | "step4b" | "step6" | "step8"> } => __stub),
  deleteForTest: _t.procedure.input((x: unknown) => x as { stepKeys?: undefined | Array<string> }).mutation((): { ok: boolean } => __stub),
  }),
  stt: _t.router({
  transcribe: _t.procedure.input((x: unknown) => x as { audioBase64: string; traceId?: undefined | string; mimeType?: undefined | string }).mutation((): { transcript: string; durationSec: number; costUsd: number } => __stub),
  }),
  tts: _t.router({
  synthesize: _t.procedure.input((x: unknown) => x as { text: string; traceId?: undefined | string; voice?: undefined | string }).mutation((): { publicUrl: string; sizeBytes: number; costUsd: number } => __stub),
  }),
  copywriting: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { stepKey: string; length?: undefined | "medium" | "short" | "long"; tone?: undefined | string; context?: undefined | Record<string, unknown> }).mutation((): { traceId: null | string; id: number; agentId: string; content: string; createdAt: Date } => __stub),
  optimize: _t.procedure.input((x: unknown) => x as { historyId: number; instruction: string }).mutation((): { traceId: null | string; id: number; agentId: string; content: string; createdAt: Date } => __stub),
  list: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number; stepKey?: undefined | string }).query((): Array<{ traceId: null | string; id: number; agentId: string; content: string; createdAt: Date }> => __stub),
  delete: _t.procedure.input((x: unknown) => x as { historyId: number }).mutation((): { ok: boolean } => __stub),
  freeGenerate: _t.procedure.input((x: unknown) => x as { topic: string; scriptType: "tutorial" | "review" | "case_study" | "pov" | "monologue" | "debate" | "list_pop" | "before_after" | "street_interview" | "qa_short" | "reaction" | "mixcut" | "screen_record" | "animation" | "vlog" | "plot" | "voice_only" | "comparison" | "storytelling" | "duo_chat"; elements: Array<"list" | "greed" | "fear" | "curiosity" | "contrast" | "resonance" | "empathy" | "social_proof" | "authority" | "leverage" | "worst" | "reveal" | "controversy" | "challenge" | "transformation" | "anger" | "surprise" | "trend" | "scarcity" | "small_big" | "low_cost_high" | "low_cost_unknown"> }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  acquisitionGenerate: _t.procedure.input((x: unknown) => x as { topic: string; conversionGoal: string; scriptType: "tutorial" | "review" | "case_study" | "pov" | "monologue" | "debate" | "list_pop" | "before_after" | "street_interview" | "qa_short" | "reaction" | "mixcut" | "screen_record" | "animation" | "vlog" | "plot" | "voice_only" | "comparison" | "storytelling" | "duo_chat"; elements: Array<"list" | "greed" | "fear" | "curiosity" | "contrast" | "resonance" | "empathy" | "social_proof" | "authority" | "leverage" | "worst" | "reveal" | "controversy" | "challenge" | "transformation" | "anger" | "surprise" | "trend" | "scarcity" | "small_big" | "low_cost_high" | "low_cost_unknown"> }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  videoAnalysis: _t.router({
  analyze: _t.procedure.input((x: unknown) => x as { lastCopy: string; lastTitle?: undefined | string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  videoProduction: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { sourceCopy: string; duration?: undefined | "15s" | "30s" | "60s" | "180s"; videoType?: undefined | "short_form" | "long_form"; additionalContext?: undefined | string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  generateStoryboard: _t.procedure.input((x: unknown) => x as { stepKey: string; style?: undefined | string; sceneCount?: undefined | number }).mutation((): { traceId: null | string; id: number; agentId: string; content: string; createdAt: Date } => __stub),
  generateSceneImage: _t.procedure.input((x: unknown) => x as { imagePromptEn: string; storyboardHistoryId: number; sceneIndex: number; imageStyle?: undefined | "vivid" | "natural" }).mutation((): { jobId: undefined | string; historyId: number; sceneIndex: number } => __stub),
  }),
  boomGenerate: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { elements: Array<"list" | "greed" | "fear" | "curiosity" | "contrast" | "resonance" | "empathy" | "social_proof" | "authority" | "leverage" | "worst" | "reveal" | "controversy" | "challenge" | "transformation" | "anger" | "surprise" | "trend" | "scarcity" | "small_big" | "low_cost_high" | "low_cost_unknown">; industry?: undefined | string; theme?: undefined | string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  monetization: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { ipPositioning?: undefined | string; industryContext?: undefined | string; audienceProfile?: undefined | string; productDescription?: undefined | string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  myTopics: _t.router({
  list: _t.procedure.input((x: unknown) => x as { search?: undefined | string; industry?: undefined | string; source?: undefined | "trending" | "step5" | "all" | "manual"; page?: undefined | number; pageSize?: undefined | number }).query((): { items: Array<{ id: string; title: string; source: "trending" | "step5" | "manual"; industry: null | string; platform: null | string; createdAt: string | Date; topicId?: undefined | number; trendingItemId?: undefined | number }>; total: number; page: number; pageSize: number; totalPages: number } => __stub),
  add: _t.procedure.input((x: unknown) => x as { title: string; industry?: undefined | string; platform?: undefined | string }).mutation((): { id: string; title: string; source: "manual"; industry: null | string; platform: null | string; createdAt: Date; topicId: number } => __stub),
  update: _t.procedure.input((x: unknown) => x as { topicId: number; industry?: undefined | string; platform?: undefined | string; title?: undefined | string }).mutation((): null | { id: string; title: string; source: "manual"; industry: null | string; platform: null | string; createdAt: Date; topicId: number } => __stub),
  delete: _t.procedure.input((x: unknown) => x as { id: string }).mutation((): { ok: boolean } => __stub),
  countBySource: _t.procedure.query((): { step5: number; trending: number; manual: number } => __stub),
  }),
  presentStyles: _t.router({
  recommend: _t.procedure.input((x: unknown) => x as { platform: string; text: string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  privateDomain: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { ipPositioning: string; targetAudience: string; productDescription: string; phase: "welcome" | "warmup" | "trust" | "discover" | "close" | "follow"; productPrice: number; currentChannel: "douyin" | "xiaohongshu" | "wechat" | "weibo" | "other"; monthlyTraffic: number; scene?: undefined | string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  generateStream: _t.procedure.input((x: unknown) => x as { ipPositioning: string; targetAudience: string; productDescription: string; phase: "welcome" | "warmup" | "trust" | "discover" | "close" | "follow"; productPrice: number; currentChannel: "douyin" | "xiaohongshu" | "wechat" | "weibo" | "other"; monthlyTraffic: number; scene?: undefined | string }).subscription((): AsyncGenerator<unknown> => __stub),
  }),
  diagnosis: _t.router({
  generate: _t.procedure.input((x: unknown) => x as { answers: Array<{ dimension: string; score: number; comment?: undefined | string }>; inferredStage?: undefined | string }).mutation((): { traceId: null | string; id: number; agentId: string; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date; answers: JsonValue; inferredStage: string; dimensions: JsonValue; overallScore: number; topPriority: string; recommendedSteps: Array<string> } => __stub),
  history: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number }).query((): Array<{ traceId: null | string; id: number; agentId: string; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date; answers: JsonValue; inferredStage: string; dimensions: JsonValue; overallScore: number; topPriority: string; recommendedSteps: Array<string> }> => __stub),
  latest: _t.procedure.query((): null | { traceId: null | string; id: number; agentId: string; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date; answers: JsonValue; inferredStage: string; dimensions: JsonValue; overallScore: number; topPriority: string; recommendedSteps: Array<string> } => __stub),
  }),
  deepLearning: _t.router({
  list: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number; onlyActive?: undefined | false | true }).query((): Array<{ id: number; sample: string; sourcePlatform: string; coreFormula: string; status: string; createdAt: Date }> => __stub),
  create: _t.procedure.input((x: unknown) => x as { sample: string; userTags?: undefined | Array<string>; userTitle?: undefined | string }).mutation((): { ok: true; queueId: number; status: string } => __stub),
  createFromFile: _t.procedure.input((x: unknown) => x as { fileUrl: string; userTags?: undefined | Array<string>; userTitle?: undefined | string }).mutation((): { ok: true; queueId: number; status: string } => __stub),
  learn: _t.procedure.input((x: unknown) => x as { samples: Array<{ text: string; source: string }> }).mutation((): { jobId: string; status: "queued" } => __stub),
  learnStatus: _t.procedure.input((x: unknown) => x as { jobId: string }).query((): { status: "completed" | "failed" | "queued" | "processing"; result: null | { summary: string; dimensions: { tone: string; structure: string; hook: string; transition: string; closing: string }; isFallback: boolean; tokensUsed: number; modelUsed: string; durationMs: number } } => __stub),
  delete: _t.procedure.input((x: unknown) => x as { archiveId: number }).mutation((): { ok: boolean } => __stub),
  parse: _t.procedure.input((x: unknown) => x as { sample: string; sourcePlatform: string }).mutation((): { queueId: number; analysis: { coreFormula: string; hookType: string; structurePattern: string; emotionalArc: string; keywords: Array<string> } } => __stub),
  applyFormula: _t.procedure.input((x: unknown) => x as { queueId: number; newTopic: string }).mutation((): { content: string } => __stub),
  }),
  knowledge: _t.router({
  list: _t.procedure.input((x: unknown) => x as { type?: undefined | "case" | "formula" | "element"; limit?: undefined | number; offset?: undefined | number }).query((): Array<{ type: "case" | "formula" | "element"; id: number; content: string; title: string; metadata: Record<string, unknown>; tokens: number; similarity?: undefined | number }> => __stub),
  search: _t.procedure.input((x: unknown) => x as { query: string; type?: undefined | "case" | "formula" | "element"; topK?: undefined | number }).mutation((): Array<{ type: "case" | "formula" | "element"; id: number; content: string; title: string; metadata: Record<string, unknown>; tokens: number; similarity?: undefined | number }> => __stub),
  getById: _t.procedure.input((x: unknown) => x as { id: number }).query((): null | { type: "case" | "formula" | "element"; id: number; content: string; title: string; metadata: Record<string, unknown>; tokens: number; similarity?: undefined | number } => __stub),
  getRecommendations: _t.procedure.input((x: unknown) => x as { limit?: undefined | number }).query((): Array<{ itemType: string; itemKey: string; title: string }> => __stub),
  getScriptCases: _t.procedure.input((x: unknown) => x as { industry?: undefined | string; limit?: undefined | number }).query((): Array<{ itemType: string; itemKey: string; title: string; industry: null | string }> => __stub),
  getFavorites: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number; itemType?: undefined | string }).query((): Array<{ id: number; accountId: number; createdAt: Date; userTags: Array<string>; itemType: string; itemKey: string; noteId: null | number }> => __stub),
  addFavorite: _t.procedure.input((x: unknown) => x as { itemType: string; itemKey: string; userTags?: undefined | Array<string> }).mutation((): { id: number; accountId: number; createdAt: Date; userTags: Array<string>; itemType: string; itemKey: string; noteId: null | number } => __stub),
  removeFavorite: _t.procedure.input((x: unknown) => x as { itemType: string; itemKey: string }).mutation((): { ok: boolean } => __stub),
  getNotes: _t.procedure.input((x: unknown) => x as { limit?: undefined | number; offset?: undefined | number; itemType?: undefined | string; itemKey?: undefined | string }).query((): Array<{ id: number; accountId: number; content: string; createdAt: Date; updatedAt: Date; title: null | string; itemType: null | string; itemKey: null | string; tags: Array<string> }> => __stub),
  addNote: _t.procedure.input((x: unknown) => x as { content: string; title?: undefined | string; itemType?: undefined | string; itemKey?: undefined | string; tags?: undefined | Array<string> }).mutation((): { id: number; accountId: number; content: string; createdAt: Date; updatedAt: Date; title: null | string; itemType: null | string; itemKey: null | string; tags: Array<string> } => __stub),
  }),
  trending: _t.router({
  list: _t.procedure.input((x: unknown) => x as { search?: undefined | string; industry?: undefined | string; sort?: undefined | "likeCount" | "commentCount" | "shareCount" | "collectCount"; page?: undefined | number; pageSize?: undefined | number; platforms?: undefined | Array<"douyin" | "xiaohongshu" | "kuaishou" | "bilibili" | "weibo" | "shipinhao">; timeRange?: undefined | "today" | "week" | "month" | "quarter" }).query((): { items: Array<{ collectCount: number; isFavorited: boolean; rank: number; industry: null | string; platform: string; id: number; title: string; presentStyle: null | string; likeCount: number; commentCount: number; shareCount: number; sourceUrl: null | string; crawledAt: Date }>; total: number; page: number; pageSize: number; totalPages: number } => __stub),
  listWithFavorites: _t.procedure.input((x: unknown) => x as { search?: undefined | string; industry?: undefined | string; sort?: undefined | "likeCount" | "commentCount" | "shareCount" | "collectCount"; page?: undefined | number; pageSize?: undefined | number; platforms?: undefined | Array<"douyin" | "xiaohongshu" | "kuaishou" | "bilibili" | "weibo" | "shipinhao">; timeRange?: undefined | "today" | "week" | "month" | "quarter" }).query((): { items: Array<{ collectCount: number; isFavorited: boolean; rank: number; industry: null | string; platform: string; id: number; title: string; presentStyle: null | string; likeCount: number; commentCount: number; shareCount: number; sourceUrl: null | string; crawledAt: Date }>; total: number; page: number; pageSize: number; totalPages: number } => __stub),
  favorite: _t.procedure.input((x: unknown) => x as { action: "add" | "remove"; trendingItemId: number }).mutation((): { favorited: boolean; skipped?: undefined | false | true } => __stub),
  detail: _t.procedure.input((x: unknown) => x as { id: number }).query((): { industry: null | string; platform: string; id: number; title: string; presentStyle: null | string; likeCount: number; commentCount: number; shareCount: number; sourceUrl: null | string; contentText: null | string; authorName: null | string; crawledAt: Date } => __stub),
  kpiStats: _t.procedure.query((): { total: number; weekNew: number; myFavorites: number; lastUpdatedAt: Date } => __stub),
  fetch: _t.procedure.input((x: unknown) => x as { platform?: undefined | string; limit?: undefined | number }).query((): Array<{ id: number; platform: "douyin" | "xiaohongshu" | "kuaishou" | "bilibili" | "weibo" | "shipinhao"; title: string; industry: string; presentStyle: null | string; likeCount: number; shareCount: number; commentCount: number; crawledAt: Date }> => __stub),
  listByIndustry: _t.procedure.input((x: unknown) => x as { industry: string; limit?: undefined | number }).query((): Array<{ industry: string; id: number; platform: "douyin" | "xiaohongshu" | "kuaishou" | "bilibili" | "weibo" | "shipinhao"; sourceUrl: string; title: string; contentText: string; presentStyle: null | string; likeCount: number; commentCount: number; shareCount: number; collectCount: number; crawledAt: Date }> => __stub),
  listByStyle: _t.procedure.input((x: unknown) => x as { presentStyle: string; limit?: undefined | number }).query((): Array<{ presentStyle: string; id: number; platform: "douyin" | "xiaohongshu" | "kuaishou" | "bilibili" | "weibo" | "shipinhao"; sourceUrl: string; title: string; contentText: string; industry: string; likeCount: number; commentCount: number; shareCount: number; collectCount: number; crawledAt: Date }> => __stub),
  }),
  invite: _t.router({
  redeem: _t.procedure.input((x: unknown) => x as { code: string }).mutation((): { code: string; id: number; createdAt: Date; isActive: boolean; usedAt: null | Date; maxUses: number; usedCount: number; expiresAt: null | Date; usedById: null | number } => __stub),
  }),
  costLog: _t.router({
  logFeedback: _t.procedure.input((x: unknown) => x as { type: "good" | "bad"; agentId: string; stepKey: string; traceId?: undefined | string }).mutation((): { ok: boolean } => __stub),
  }),
  analysis: _t.router({
  analyze: _t.procedure.input((x: unknown) => x as { copy: string }).mutation((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; tokensUsed: null | number; modelUsed: null | string; durationMs: null | number; isFallback: boolean; createdAt: Date } => __stub),
  }),
  history: _t.router({
  count: _t.procedure.input((x: unknown) => x as undefined | { dateRange?: undefined | "custom" | "all" | "today" | "week" | "month" | "last_7d" | "last_30d"; dateFrom?: undefined | string; dateTo?: undefined | string }).query((): number => __stub),
  list: _t.procedure.input((x: unknown) => x as { agentId?: undefined | string; agentMode?: undefined | string; sourceType?: undefined | string; limit?: undefined | number; offset?: undefined | number; dateRange?: undefined | "custom" | "all" | "today" | "week" | "month" | "last_7d" | "last_30d"; dateFrom?: undefined | string; dateTo?: undefined | string; tools?: undefined | Array<string> }).query((): Array<{ traceId: null | string; id: number; agentId: string; agentMode: null | string; sourceType: string; inputSummary: string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; isFallback: boolean; createdAt: Date }> => __stub),
  detail: _t.procedure.input((x: unknown) => x as { id: number }).query((): { traceId: null | string; id: number; agentId: string; agentMode: null | string; sourceType: string; inputSummary: string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; isFallback: boolean; createdAt: Date } | { scenes: Array<{ index: number; description: string; imagePromptEn: string; duration: string; status: "pending" | "completed" | "failed"; sceneImageUrl: null | string }>; traceId: null | string; id: number; agentId: string; agentMode: null | string; sourceType: string; inputSummary: string; content: string; contentType: string; scriptType: null | string; elements: Array<string>; isFallback: boolean; createdAt: Date } => __stub),
  delete: _t.procedure.input((x: unknown) => x as { id: number }).mutation((): { ok: true } => __stub),
  stats: _t.procedure.input((x: unknown) => x as { dateRange?: undefined | "custom" | "all" | "today" | "week" | "month"; dateFrom?: undefined | string; dateTo?: undefined | string; tools?: undefined | Array<string> }).query((): { totalCalls: number; failureRate: number; avgDurationMs: number; topTools: Array<{ agentId: string; count: number }>; dailyTrend: Array<{ date: string; count: number }>; durationHistogram: Array<{ label: string; count: number }>; modelDistribution: Array<{ model: string; count: number }> } => __stub),
  }),
  voiceChat: _t.router({
  start: _t.procedure.input((x: unknown) => x as { userMessage: string; traceId?: undefined | string; sessionId?: undefined | string }).subscription((): AsyncGenerator<unknown> => __stub),
  clearSession: _t.procedure.mutation((): { ok: boolean } => __stub),
  }),
});

export type AppRouter = typeof _gen;
